# -Elkethe Tank Monitoring-
# MAINTAINER Christos Vasilakis <cvasilak@gmail.com>

version: '2'

services:

  data:
    image: alpine:3.3
    command: echo Data Container
    user: 999:999
    labels:
      org.cvasilak.elkethe.app: "Tanks"
      org.cvasilak.elkethe.tanks.role: "Volume Container"

  dbinfluxdb:
    extends:
      file: docker-compose.yml
      service: data
    volumes:
      - /var/influxdb:/data

  dbgrafana:
    extends:
      file: docker-compose.yml
      service: data
    volumes:
      - /var/lib/grafana

  influxdb:
    build: ./influxdb
    restart: always
    volumes_from:
      - dbinfluxdb
    env_file: .influxdb.env
    labels:
      org.cvasilak.elkethe.app: "Tanks"
      org.cvasilak.elkethe.tanks.role: "InfluxDB Database"

  mosquitto:
    build: ./mosquitto
    restart: always
    links:
      - influxdb
    environment:
      - SERVICE_NAME=mosquitto
    ports:
      - "1883:1883" # expose native mqtt port
      - "9001:9001" # expose websocket port
    labels:
      org.cvasilak.elkethe.app: "Tanks"
      org.cvasilak.elkethe.tanks.role: "Mosquitto MQTT"

  mqbridge:
    build: ./mqbridge
    env_file: .mqbridge.env
    restart: always
    links:
      - mosquitto
    environment:
      - SERVICE_NAME=mqbridge
    labels:
      org.cvasilak.elkethe.app: "Tanks"
      org.cvasilak.elkethe.tanks.role: "Hawkular MQTT-bridge"

  grafana:
    build: ./grafana
    env_file: .grafana.env
    volumes_from:
      - dbgrafana
    restart: always
    links:
      - influxdb
    environment:
      - SERVICE_NAME=grafana
    ports:
      - "80:3000"
    labels:
      org.cvasilak.elkethe.app: "Tanks"
      org.cvasilak.elkethe.tanks.role: "Grafana"
