FROM alpine:3.3
MAINTAINER Christos Vasilakis <cvasilak@gmail.com>

ENV BUILD_PACKAGES bash ruby-dev build-base git
ENV RUBY_PACKAGES ruby ruby-io-console ruby-bundler

RUN apk update && \
    apk upgrade && \
    apk add $BUILD_PACKAGES && \
    apk add $RUBY_PACKAGES && \
    rm -rf /var/cache/apk/*

RUN mkdir /usr/app
WORKDIR /usr/app

COPY Gemfile /usr/app/
COPY Gemfile.lock /usr/app/
RUN bundle install

COPY . /usr/app

CMD ["ruby", "mqbridge.rb"]